packages:
  - "images/*"

allowBuilds:
  edgedriver: true
  esbuild: true
  geckodriver: true
  vue-demi: true

injectWorkspacePackages: true

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
