packages:
  - "images/*"

allowBuilds:
  "@tree-sitter-grammars/tree-sitter-hcl": true
  edgedriver: true
  esbuild: true
  geckodriver: true
  tree-sitter: true
  vue-demi: true

injectWorkspacePackages: true

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
