# Example Wikibase docker compose setup
version: '3.5'

x-common-variables: &wikibase_variables
  WIKIBASE_HOST: ${WIKIBASE_HOST}
  DB_SERVER: ${DB_HOST}:${DB_PORT}
  MW_ADMIN_NAME: ${MW_ADMIN_NAME}
  MW_ADMIN_PASS: ${MW_ADMIN_PASS}
  MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
  MW_WG_SECRET_KEY: ${MW_SECRET_KEY}
  # Disable jobs running after requests when wikibase-jobrunner is defined
  MW_WG_JOB_RUN_RATE: 0
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_NAME: ${DB_NAME}

name: ${DOCKER_PROJECT_NAME}

services:

  wikibase:
    image: "${WIKIBASE_SUITE_WIKIBASE_BUNDLE_IMAGE_URL}"
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "${WIKIBASE_PORT}:80"
    volumes:
      ## This shares the configuration with jobrunner
      - shared:/var/www/html/:rw
      ## Uncomment this next line to mount your own LocalSettings.php file
      ## also uncomment the same line in the wikibase-jobrunner service!
      #- ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
    networks:
      default:
        aliases:
          - ${WIKIBASE_HOST}
    environment:
      <<: *wikibase_variables
      VIRTUAL_HOST: ${WIKIBASE_HOST}
      WIKIBASE_PINGBACK:
      MW_WG_ENABLE_UPLOADS:
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://${WIKIBASE_HOST}/wiki/Main_Page" ]
      interval: 10s
      start_period: 2m

  wikibase-jobrunner:
    image: "${WIKIBASE_SUITE_WIKIBASE_BUNDLE_IMAGE_URL}"
    entrypoint: /bin/bash
    command:  /jobrunner-entrypoint.sh
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    volumes:
      - shared:/shared/:ro
      - ./jobrunner-entrypoint.sh:/jobrunner-entrypoint.sh
      ## Uncomment this next line to mount your own LocalSettings.php file
      ## also uncomment the same line in the wikibase service
      #- ./LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
    environment:
      <<: *wikibase_variables
      MAX_JOBS: ${MAX_JOBS}

  mysql:
    image: "${MARIADB_IMAGE_URL}"
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    networks:
      default:
        aliases:
          - ${DB_HOST}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 20s
      timeout: 5s

volumes:
  shared:
  mediawiki-mysql-data:
