version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /test/
    schedule:
      interval: weekly
    commit-message:
      prefix: npm
      include: scope
    groups:
      lint:
        patterns:
          - "*eslint*"
          - "prettier*"
          - "stylelint*"
      "@wdio":
        patterns:
          - "@wdio/*"
