#!/bin/bash

# Ensure the script exits on error
set -e

IMAGE_NAME="nx-runner:latest"

# Check if we're in a CI environment
if [ "$CI" = "true" ]; then
  echo "Running in CI mode"
  npm ci
  npx nx "$@"
else
  # Get the current working directory
  WORKDIR=$(pwd)
  docker build -q -t $IMAGE_NAME . > /dev/null
  # Run the Nx command inside the Docker container
  docker run --rm -it \
    -v "$WORKDIR:/workspace" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -w /workspace \
    $IMAGE_NAME "$@"
fi
