#!/usr/bin/env bash
set -euo pipefail

# --- Expected Variables ---

export WBS_DIR
export SCRIPTS_DIR
export TOOLS_DIR

# --- Bootstrap Logging ---

# shellcheck disable=SC1091
source "$SCRIPTS_DIR/_logging.sh"

BUILD_COMPOSE_TEMPLATE="$TOOLS_DIR/docker-compose.build.yml"
BUILD_COMPOSE_FILE="$WBS_DIR/docker-compose.build.yml"
BUILD_COMPOSE_MARKER="# Generated by wbs install --build."

if [[ -f "$BUILD_COMPOSE_FILE" ]] &&
  [[ "$(head -n 1 "$BUILD_COMPOSE_FILE")" != "$BUILD_COMPOSE_MARKER" ]]; then
  status "⛔️ Refusing to replace the existing docker-compose.build.yml because it was not generated by wbs install --build." "build_override_conflict"
  exit 1
fi

image_projects=()
for dockerfile in "$WBS_DIR"/development/images/*/Dockerfile; do
  image_project="$(basename "$(dirname "$dockerfile")")"
  if [[ "$image_project" != "wbs-tools" ]]; then
    image_projects+=( "$image_project" )
  fi
done

if [[ "${#image_projects[@]}" -eq 0 ]]; then
  status "⛔️ No product image projects were found in the selected source checkout." "image_projects_missing"
  exit 1
fi

status "Building Wikibase Suite images from the selected source checkout..." "images_build_started"
"$WBS_DIR/development/wbs-dev" build "${image_projects[@]}"
cp "$BUILD_COMPOSE_TEMPLATE" "$BUILD_COMPOSE_FILE"
status "✅ All source image builds are current." "images_build_ready"
status "Locally built images will remain selected through docker-compose.build.yml. Remove that file to return to published images." "source_build_override_created"
