name: "push-ghcr"
description: "Push to GHCR"
inputs:
  docker_image:
    description: "name of the docker image to push"
    required: true
  github_token:
    description: "token to access GHCR"
    required: true

runs:
  using: "composite"

  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - shell: bash
      run: |
        set -x

        docker image ls

        # Get the docker tag name != latest of the image we are currently looking at. (The version string that is)
        version_tag=$(docker image ls | grep -e '^${{ inputs.docker_image }} ' | grep -v latest | awk '{print $2}' | head -n 1)

        # We need to retag the container for GHCR because the current tag is targetting docker hub.
        from_url=${{ inputs.docker_image }}:"$version_tag"

        # A tag containing the version string.
        to_url_version="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image }}:dev-${version_tag}"
        docker tag "$from_url" "$to_url_version"
        docker push "$to_url_version"

        # A tag containing the github run id.
        to_url_run_id="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image }}:dev-${{ github.run_id }}"
        docker tag "$from_url" "$to_url_run_id"
        docker push "$to_url_run_id"

        # A tag containing the branch name if available.
        if [ -n "${{ github.head_ref }}" ]; then
          to_url_branch="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image }}:dev-${{ github.head_ref }}"
          docker tag "$from_url" "$to_url_branch"
          docker push "$to_url_branch"
        fi
