name: scan-image
description: Scan image and upload results
inputs:
  image_name:
    description: name of the docker image to work with
    required: true

runs:
  using: composite

  steps:
    - uses: anchore/scan-action@v3
      id: scan
      with:
        severity-cutoff: critical
        fail-build: false
        image: ${{ inputs.image_name }}

    # As this step depends on github.event.pull_request it never
    # ran until https://github.com/wmde/wikibase-release-pipeline/pull/317 was done
    # So disable it in that PR and fix it in a followup...
    # uploads it to the ui
    # - uses: github/codeql-action/upload-sarif@v1
    #   if: |
    #     github.actor != 'dependabot[bot]' &&
    #     (github.event.pull_request.head.repo.full_name == github.repository)
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Inspect action SARIF report
      shell: bash
      run: |
        cat ${{ steps.scan.outputs.sarif }}
        mkdir -p /tmp/sarif-reports
        cp ${{ steps.scan.outputs.sarif }} /tmp/sarif-reports/${{ inputs.image_name }}.sarif

    - name: Archive scan artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ScanResults
        if-no-files-found: error
        path: /tmp/sarif-reports/${{ inputs.image_name }}.sarif
