name: 'checkout-and-prepare'
description: 'Upload builds as artifacts and to GHCR'

inputs:
  name:
    description: 'the name of the built artifact'
    required: true
  channel:
    description: 'the channel this artifact was built for'
    required: true
  # filename:
  #   description: 'the filename of the built artifact'
  #   required: true
  # imagename:
  #   description: 'the docker image name of the built artifact'
  #   required: true
  # tarname:
  #   description: 'the tar file name of the built artifact'
  #   required: true
  github_token:
    description: 'secret token to upload to github container registry'
    required: true


runs:
  using: "composite"
  steps:
      # - name: Archive metadata artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: BuildMetadata
      #     if-no-files-found: error
      #     path: artifacts/build_metadata_${{ inputs.name }}.env

      - name: Archive tar Artifacts (if any)
        uses: actions/upload-artifact@v3
        with:
          name: BuildArtifactsTar-${{ inputs.channel }}
          if-no-files-found: warn
          path: artifacts/${{ inputs.name }}.tar.gz

      - name: Archive Docker Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuildArtifactsDocker-${{ inputs.channel }}
          if-no-files-found: error
          path: artifacts/${{ inputs.name }}.docker.tar.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ inputs.github_token }}

      - name: Store release version docker image on GHCR
        if: github.ref == 'refs/heads/main'
        uses: wmde/tag-push-ghcr-action@v3
        with:
          image_name: "wikibase/${{ inputs.name }}"
          tag: ${{ github.run_id }}

