name: "checkout-and-prepare"
description: "Upload builds as artifacts and to GHCR"

inputs:
  name:
    description: "the name of the built artifact"
    required: true
  channel:
    description: "the channel this artifact was built for"
    required: true

runs:
  using: "composite"
  steps:
    - name: Archive build_metadata Artifacts (if any)
      uses: actions/upload-artifact@v3
      with:
        name: Metadata-${{ inputs.channel }}
        path: artifacts/build_metadata_${{ inputs.name }}.env
        if-no-files-found: ignore


    - name: Archive tar artifacts (if any)
      uses: actions/upload-artifact@v3
      with:
        name: TarBalls-${{ inputs.channel }}
        path: artifacts/${{ inputs.name }}.tar.gz
        if-no-files-found: ignore

    - name: Archive Docker artifact
      uses: actions/upload-artifact@v3
      with:
        name: DockerImages-${{ inputs.channel }}
        path: artifacts/${{ inputs.name }}.docker.tar.gz
        if-no-files-found: error
