<?php

# Preserve intentional choices made by the MediaWiki installer configuration
# previously generated by WBS. Settings equal to MediaWiki defaults are omitted.
$wbsDefaultLogo = "$wgScriptPath/extensions/WikibaseSuite/resources/wikibase-logo.webp";
$wgLogos = [
	# Complete Wikibase lockup for legacy skins and Vector's top-left wordmark.
	'1x' => $wbsDefaultLogo,
	'wordmark' => [
		'src' => $wbsDefaultLogo,
		'width' => 84,
		'height' => 50,
	],
];

$wgEmergencyContact = '';
$wgPasswordSender = '';

if ( !in_array( 'actor', $wgSharedTables, true ) ) {
	$wgSharedTables[] = 'actor';
}

$wgMainCacheType = CACHE_ACCEL;
$wgSessionCacheType = CACHE_DB;
$wgMemCachedServers = [];
$wgUseImageMagick = true;

$wgRightsPage = '';
$wgRightsUrl = '';
$wgRightsText = '';
$wgRightsIcon = '';

wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# JobRunner instance is assumed by default, so jobs on request is disabled
$wgJobRunRate = 0;

# File Uploads enabled by default
$wgEnableUploads = true;

# Logs
# TODO: Explore simply logging to stdout/stderr so these appear in Docker logs
$wgDebugLogGroups = array(
	'resourceloader' => '/var/log/mediawiki/mw.resourceloader.log',
	'exception' => '/var/log/mediawiki/mw.exception.log',
	'error' => '/var/log/mediawiki/mw.error.log',
	'fatal' => '/var/log/mediawiki/mw.fatal.log',
);
$wgDebugLogFile = '/var/log/mediawiki/mw.debug.log';

$wgArticlePath = "/wiki/$1";

# Disable anonymous write access by default while keeping anonymous read access.
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['writeapi'] = false;
$wgGroupPermissions['*']['createaccount'] = false;

# Settings managed by the WBS configuration panel. LocalSettings.php loads
# afterward and remains the final override for advanced/manual configuration.
$wbsManagedConfigPath = '/config/WBSConfig.json';
if ( is_readable( $wbsManagedConfigPath ) ) {
	$wbsManagedConfig = json_decode( file_get_contents( $wbsManagedConfigPath ), true );
	if ( is_array( $wbsManagedConfig ) ) {
		if ( isset( $wbsManagedConfig['siteName'] ) && is_string( $wbsManagedConfig['siteName'] ) ) {
			$wgSitename = $wbsManagedConfig['siteName'];
		}
		$wbsAccess = $wbsManagedConfig['access'] ?? [];
		if ( is_array( $wbsAccess ) ) {
			$wgGroupPermissions['*']['read'] = $wbsAccess['publicRead'] ?? true;
			$wgGroupPermissions['*']['createaccount'] = $wbsAccess['accountRegistration'] ?? false;
			$wgGroupPermissions['*']['edit'] = $wbsAccess['anonymousEditing'] ?? false;
			$wgGroupPermissions['*']['writeapi'] = $wbsAccess['anonymousEditing'] ?? false;
			$wgGroupPermissions['*']['createtalk'] = $wbsAccess['anonymousEditing'] ?? false;
			$wgGroupPermissions['*']['createpage'] = $wbsAccess['anonymousItemCreation'] ?? false;
			$wgGroupPermissions['*']['property-create'] = $wbsAccess['anonymousPropertyCreation'] ?? false;
			$wgEnableUploads = $wbsAccess['uploads'] ?? true;
		}
	}
}
