#!/usr/bin/env bash
set -e

echo "🔧 Wikibase Deploy CLI Installer"

# --- Expected env vars ---
DEPLOY_DIR="${DEPLOY_DIR:?DEPLOY_DIR not set}"
LOG_PATH="${LOG_PATH:-/tmp/wbs-deploy-setup.log}"
VERBOSE="${VERBOSE:-false}"
LOCALHOST="${LOCALHOST:-false}"

# --- Setup logging ---
# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_logging.sh"

ENV_FILE_PATH="$DEPLOY_DIR/.env"

if [ "$LOCALHOST" = true ]; then
  WIKIBASE_PUBLIC_HOST=localhost
  WDQS_PUBLIC_HOST=localhost
else
  PUBLIC_IP=$(curl --silent --show-error --fail https://api.ipify.org)
fi

read -rp "Admin Email Address: " MW_ADMIN_EMAIL

WIKIBASE_PUBLIC_HOST_DEFAULT=${WIKIBASE_PUBLIC_HOST:-$PUBLIC_IP.nip.io}
read -rp "Wikibase Public Host [${WIKIBASE_PUBLIC_HOST_DEFAULT}]: " WIKIBASE_PUBLIC_HOST
WIKIBASE_PUBLIC_HOST=${WIKIBASE_PUBLIC_HOST:-$WIKIBASE_PUBLIC_HOST_DEFAULT}

WDQS_PUBLIC_HOST_DEFAULT=${WDQS_PUBLIC_HOST:-query.$WIKIBASE_PUBLIC_HOST}
read -rp "Query Service Host [$WDQS_PUBLIC_HOST_DEFAULT]: " WDQS_PUBLIC_HOST
WDQS_PUBLIC_HOST=${WDQS_PUBLIC_HOST:-$WDQS_PUBLIC_HOST_DEFAULT}

read -rp "MediaWiki Admin Username [Admin]: " MW_ADMIN_NAME
MW_ADMIN_NAME=${MW_ADMIN_NAME:-Admin}

# Admin Password
while true; do
  read -rsp "MediaWiki Admin Password [autogenerated]: " MW_ADMIN_PASS
  echo
  if [ -z "$MW_ADMIN_PASS" ]; then
    MW_ADMIN_PASS=$(openssl rand -base64 8 | tr -dc 'a-zA-Z0-9' | cut -c1-10)
    break
  elif [ ${#MW_ADMIN_PASS} -lt 10 ]; then
    echo "❌ Password must be at least 10 characters. Try again."
  else
    break
  fi
done

# Database Password
while true; do
  read -rsp "Database Password [autogenerated]: " DB_PASS
  echo
  if [ -z "$DB_PASS" ]; then
    DB_PASS=$(openssl rand -base64 8 | tr -dc 'a-zA-Z0-9' | cut -c1-10)
    break
  elif [ ${#DB_PASS} -lt 10 ]; then
    echo "❌ Password must be at least 10 characters. Try again."
  else
    break
  fi
done

read -rp "Database Name [my_wiki]: " DB_NAME
DB_NAME=${DB_NAME:-my_wiki}

read -rp "Database User [sqluser]: " DB_USER
DB_USER=${DB_USER:-sqluser}

read -rp "Expose this Wikibase to global directory? (y/n) [y]: " METADATA_CALLBACK
METADATA_CALLBACK=${METADATA_CALLBACK,,}  # lowercase
test "$METADATA_CALLBACK" != "n" && METADATA_CALLBACK=true || METADATA_CALLBACK=false

mkdir -p "$(dirname "$ENV_FILE_PATH")"

cat > "$ENV_FILE_PATH" <<EOF
# Autogenerated .env from CLI installer
METADATA_CALLBACK=$METADATA_CALLBACK
WIKIBASE_PUBLIC_HOST=$WIKIBASE_PUBLIC_HOST
WDQS_PUBLIC_HOST=$WDQS_PUBLIC_HOST
MW_ADMIN_NAME=$MW_ADMIN_NAME
MW_ADMIN_EMAIL=$MW_ADMIN_EMAIL
MW_ADMIN_PASS=$MW_ADMIN_PASS
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
EOF
