#!/usr/bin/env bash
set -e

echo "🔧 Wikibase Deploy CLI Installer"

# --- Parse args passed from go.sh ---
for arg in "$@"; do
  case $arg in
    --verbose=*) VERBOSE="${arg#*=}" ;;
    --deploy-dir=*) DEPLOY_DIR="${arg#*=}" ;;
    --log-path=*) LOG_PATH="${arg#*=}" ;;
    --local=*) LOCALHOST="${arg#*=}" ;;
  esac
done

# -- Setup logging -- 
# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_logging.sh"

ENV_FILE_PATH="$DEPLOY_DIR/.env"

read -rp "Admin Email Address: " MW_ADMIN_EMAIL
read -rp "Wikibase Public Host (default: $PUBLIC_IP.nip.io): " WIKIBASE_PUBLIC_HOST
WIKIBASE_PUBLIC_HOST=${WIKIBASE_PUBLIC_HOST:-$PUBLIC_IP.nip.io}

read -rp "MediaWiki Admin Username [admin]: " MW_ADMIN_NAME
MW_ADMIN_NAME=${MW_ADMIN_NAME:-admin}

# Admin Password
while true; do
  read -rsp "MediaWiki Admin Password (leave blank for autogenerated): " MW_ADMIN_PASS
  echo
  if [ -z "$MW_ADMIN_PASS" ]; then
    MW_ADMIN_PASS=$(openssl rand -base64 8 | tr -dc 'a-zA-Z0-9' | cut -c1-10)
    break
  elif [ ${#MW_ADMIN_PASS} -lt 10 ]; then
    echo "❌ Password must be at least 10 characters. Try again."
  else
    break
  fi
done

read -rp "Database Name [my_wiki]: " DB_NAME
DB_NAME=${DB_NAME:-my_wiki}

read -rp "Database User [sqluser]: " DB_USER
DB_USER=${DB_USER:-sqluser}

# Database Password
while true; do
  read -rsp "Database Password (leave blank for autogenerated): " DB_PASS
  echo
  if [ -z "$DB_PASS" ]; then
    DB_PASS=$(openssl rand -base64 8 | tr -dc 'a-zA-Z0-9' | cut -c1-10)
    break
  elif [ ${#DB_PASS} -lt 10 ]; then
    echo "❌ Password must be at least 10 characters. Try again."
  else
    break
  fi
done

read -rp "Expose this Wikibase to global directory? (y/n) [y]: " METADATA_CALLBACK
METADATA_CALLBACK=${METADATA_CALLBACK,,}  # lowercase
test "$METADATA_CALLBACK" != "n" && METADATA_CALLBACK=true || METADATA_CALLBACK=false

# Optional WDQS Host
read -rp "Query Service Host [query.$WIKIBASE_PUBLIC_HOST]: " WDQS_PUBLIC_HOST
WDQS_PUBLIC_HOST=${WDQS_PUBLIC_HOST:-query.$WIKIBASE_PUBLIC_HOST}

mkdir -p "$(dirname "$ENV_FILE_PATH")"

cat > "$ENV_FILE_PATH" <<EOF
# Autogenerated .env from CLI installer
MW_ADMIN_EMAIL=$MW_ADMIN_EMAIL
MW_ADMIN_NAME=$MW_ADMIN_NAME
MW_ADMIN_PASS=$MW_ADMIN_PASS
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
WIKIBASE_PUBLIC_HOST=$WIKIBASE_PUBLIC_HOST
WDQS_PUBLIC_HOST=$WDQS_PUBLIC_HOST
METADATA_CALLBACK=$METADATA_CALLBACK
EOF

echo
cat "$ENV_FILE_PATH"
echo

echo "✅ Configuration saved."
