name: "test-upgrade"
description: "Test upgrade"
inputs:
  version:
    description: "Version to test upgrade from"
    required: true

runs:
  using: "composite"

  steps:
    - shell: bash
      run: ./test.sh upgrade ${{ matrix.version }}

    - uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: test/suites/**/results
