http:
  services:
    wikibase:
      loadBalancer:
        servers:
          - url: "http://wikibase:80"

    wdqs:
      loadBalancer:
        servers:
          - url: "http://wdqs:9999"

    wdqs-frontend:
      loadBalancer:
        servers:
          - url: "http://wdqs-frontend:80"

    quickstatements:
      loadBalancer:
        servers:
          - url: "http://quickstatements:80"
