# traefik static configuration

# TODO: disable API before merge
api:
  dashboard: true
  insecure: true  # Set to false in production

# TODO: disable debug log before merge
log:
  level: "DEBUG"

accessLog:
  format: "common"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "letsencrypt"

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"

providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
