#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - git

runcmd:
  - curl -fsSL https://raw.githubusercontent.com/wmde/wikibase-release-pipeline/refs/heads/cloud-config-test/deploy/vps-setup.sh -o /usr/local/bin/wbs-vps-setup.sh
  - chmod +x /usr/local/bin/wbs-vps-setup.sh
  - /usr/local/bin/wbs-vps-setup.sh
