# traefik dynamic configuration

http:
  services:
    wikibase:
      loadBalancer:
        servers:
          - url: "http://wikibase:80"

    query:
      loadBalancer:
        servers:
          - url: "http://query:7001"

    query-ui:
      loadBalancer:
        servers:
          - url: "http://query-ui:80"

    quickstatements:
      loadBalancer:
        servers:
          - url: "http://quickstatements:80"

  routers:
    wikibase-router:
      rule: 'Host(`{{ env "WIKIBASE_PUBLIC_HOST" }}`) && !PathPrefix(`/tools`)'
      service: wikibase

    query-router:
      rule: 'Host(`{{ env "WDQS_PUBLIC_HOST" }}`) && PathPrefix(`/sparql`) && (Method(`GET`) || Method(`OPTIONS`) || Method(`POST`))'
      service: query
      middlewares: [ query-prefix, query-headers, query-cors-headers, query-rate-limit ]

    query-ui-router:
      rule: 'Host(`{{ env "WDQS_PUBLIC_HOST" }}`) && !PathPrefix(`/sparql`)'
      service: query-ui

    quickstatements-router:
      rule: 'Host(`{{ env "WIKIBASE_PUBLIC_HOST" }}`) && PathPrefix(`/tools/quickstatements`)'
      service: quickstatements
      middlewares: [ quickstatements-redirectregex, quickstatements-stripprefix ]

  middlewares:
    query-prefix:
      stripPrefix:
        prefixes: [ /sparql ]

    query-headers:
      headers:
        accessControlAllowMethods: "GET,OPTIONS,POST"
        customResponseHeaders:
          VARY: Accept

    query-cors-headers:
      headers:
        accessControlAllowHeaders: "*"

    query-rate-limit:
      rateLimit:
        burst: 30
        average: 60
        period: 1m

    quickstatements-redirectregex:
      redirectRegex:
        regex: /tools/quickstatements$
        replacement: /tools/quickstatements/
        permanent: true

    quickstatements-stripprefix:
      stripPrefix:
        prefixes: [ /tools/quickstatements ]
