services:
  traefik:
    image: traefik:3
    command:
      - "--accesslog.format=common"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asdefault"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${MW_ADMIN_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro
      - traefik-letsencrypt-data:/letsencrypt
    environment:
      WIKIBASE_PUBLIC_HOST: ${WIKIBASE_PUBLIC_HOST}
      WDQS_PUBLIC_HOST: ${WDQS_PUBLIC_HOST}
