name: "push-dockerhub"
description: "Push to Dockerhub"
inputs:
  docker_image:
    description: "name of the docker image to push"
    required: true
  dockerhub_token:
    description: "token to access dockerhub"
    required: true

runs:
  using: "composite"

  steps:
    - uses: docker/login-action@v3
      with:
        # implicitly docker hub
        username: "roti4wmde" # TODO: get a bot user
        password: ${{ inputs.dockerhub_token }}

    - shell: bash
      run: |
        set -x

        docker image ls

        # Get the docker tag name != latest of the image we are currently looking at. (The version string that is)
        version_tag=$(docker image ls | grep -e '^${{ inputs.docker_image }} ' | grep -v latest | awk '{print $2}' | head -n 1)

        # We need to retag the container for GHCR because the current tag is targetting docker hub.
        # We will push two tags to GHCR, a version tag and a tag representing the current CI pipeline run id.
        # Let's create "from" and "to" container URLs first.
        from_url=${{ inputs.docker_image }}:"$version_tag"
        to_url_version="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image }}:dev-${version_tag}"
        to_url_run_id="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image }}:dev-${{ github.run_id }}"
        to_url_branch="ghcr.io/${{ github.repository_owner }}/${{ inputs.docker_image }}:dev-${{ github.head_ref }}"

        # Retag and push
        docker tag "$from_url" "$to_url_version"
        docker tag "$from_url" "$to_url_run_id"
        docker tag "$from_url" "$to_url_branch"
        docker push "$to_url_version"
        docker push "$to_url_run_id"
        docker push "$to_url_branch"
