<?php

# Preserve intentional choices made by the MediaWiki installer configuration
# previously generated by WBS. Settings equal to MediaWiki defaults are omitted.

# Wikibase Suite default logo
$wgLogos = [
	'icon' => "$wgScriptPath/extensions/WikibaseSuite/resources/assets/wikibase_vertical.svg",
];

$wgEmergencyContact = '';
$wgPasswordSender = '';

if ( !in_array( 'actor', $wgSharedTables, true ) ) {
	$wgSharedTables[] = 'actor';
}

$wgMainCacheType = CACHE_ACCEL;
$wgSessionCacheType = CACHE_DB;
$wgParserCacheType = CACHE_DB;
$wgMemCachedServers = [];

# Redis is optional. When configured, it provides a shared main cache and
# session store suitable for multiple web or job-runner containers.
$wbsRedisServer = getenv( 'REDIS_SERVER' );
if ( $wbsRedisServer !== false && trim( (string)$wbsRedisServer ) !== '' ) {
	$wbsRedisOptions = [
		'class' => RedisBagOStuff::class,
		'servers' => [ trim( (string)$wbsRedisServer ) ],
		'connectTimeout' => 1,
		'persistent' => true,
	];
	$wbsRedisPassword = getenv( 'REDIS_PASSWORD' );
	if ( $wbsRedisPassword !== false && $wbsRedisPassword !== '' ) {
		$wbsRedisOptions['password'] = $wbsRedisPassword;
	}
	$wgObjectCaches['redis'] = $wbsRedisOptions;
	$wgMainCacheType = 'redis';
	$wgSessionCacheType = 'redis';
}

$wgUseImageMagick = true;

$wgRightsPage = '';
$wgRightsUrl = '';
$wgRightsText = '';
$wgRightsIcon = '';

wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# JobRunner instance is assumed by default, so jobs on request is disabled
$wgJobRunRate = 0;

# File Uploads enabled by default
$wgEnableUploads = true;

# Logs
# TODO: Explore simply logging to stdout/stderr so these appear in Docker logs
$wgDebugLogGroups = array(
	'resourceloader' => '/var/log/mediawiki/mw.resourceloader.log',
	'exception' => '/var/log/mediawiki/mw.exception.log',
	'error' => '/var/log/mediawiki/mw.error.log',
	'fatal' => '/var/log/mediawiki/mw.fatal.log',
);
$wgDebugLogFile = '/var/log/mediawiki/mw.debug.log';

$wgArticlePath = "/wiki/$1";

# Disable anonymous write access by default while keeping anonymous read access.
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['writeapi'] = false;
$wgGroupPermissions['*']['createaccount'] = false;
