name: pull-ghcr
description: Pull all images from GHCR (for current run ID)

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        set -x

        images=(
          "wikibase"
          "wikibase-lts"
          "elasticsearch"
          "wdqs"
          "wdqs-frontend"
          "wdqs-proxy"
          "quickstatements"
        )

        for i in "${images[@]}"; do
          image="wikibase/${i}"
          url_run_id="ghcr.io/${{ github.repository_owner }}/${image}:dev-${{ github.run_id }}"
          docker pull "$url_run_id"
          docker tag "$url_run_id" "${image}:latest"
        done
