name: "pull-ghcr"
description: "Pull all from GHCR"
inputs:
  github_token:
    description: "token to access GHCR"
    required: true

runs:
  using: "composite"

  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - shell: bash
      run: |
        set -x

        images=(
          "wikibase" 
          "wikibase-bundle" 
          "elasticsearch" 
          "wdqs" 
          "wdqs-frontend" 
          "wdqs-proxy" 
          "quickstatements"
        )

        for i in "${images[@]}"; do
          image="wikibase/${i}"
          url_run_id="ghcr.io/${{ github.repository_owner }}/${image}:dev-${{ github.run_id }}"
          docker pull "$url_run_id"
          docker tag "$url_run_id" "${image}:latest"
        done
