#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - netcat-openbsd
  - git

runcmd:
  - curl -fsSL https://raw.githubusercontent.com/wmde/wikibase-release-pipeline/refs/heads/cloud-config-test/deploy/setup/setup.sh | bash
