import express from 'express';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { exec } from 'child_process';
import https from 'https';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

// Setup __dirname with ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
const port = 80;
const DEPLOY_DIR = '/opt/wbs/wikibase-release-pipeline/deploy';

// Middleware
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());

// Helper to get public IP
function getPublicIP() {
  return new Promise((resolve, reject) => {
    https.get('https://api.ipify.org', (res) => {
      let ip = '';
      res.on('data', chunk => ip += chunk);
      res.on('end', () => resolve(ip.trim()));
    }).on('error', reject);
  });
}

// Helper to generate secure passwords
function generatePassword() {
  return crypto.randomBytes(12).toString('base64');
}

// Log streaming
app.get('/log', (req, res) => {
  const logPath = '/var/log/cloud-init-output.log';
  if (!fs.existsSync(logPath)) return res.status(404).send('Log not found');
  fs.readFile(logPath, 'utf8', (err, data) => {
    if (err) return res.status(500).send('Error reading log');
    res.type('text/plain').send(data);
  });
});

// Write .env
app.post('/write-env', async (req, res) => {
  const v = req.body;
  const publicIP = await getPublicIP().catch(() => '127.0.0.1');

  const env = {
    WIKIBASE_PUBLIC_HOST: v.WIKIBASE_PUBLIC_HOST || `${publicIP}.nip.io`,
    WDQS_PUBLIC_HOST: v.WDQS_PUBLIC_HOST || `query.${publicIP}.nip.io`,
    MW_ADMIN_NAME: v.MW_ADMIN_NAME || 'admin',
    MW_ADMIN_EMAIL: v.MW_ADMIN_EMAIL || 'admin@wikibase.example',
    MW_ADMIN_PASS: v.MW_ADMIN_PASS || generatePassword(),
    DB_NAME: v.DB_NAME || 'my_wiki',
    DB_USER: v.DB_USER || 'sqluser',
    DB_PASS: v.DB_PASS || generatePassword(),
    METADATA_CALLBACK: v.METADATA_CALLBACK === 'true'
  };

  const lines = [
    '# Autogenerated .env file from installer UI',
    `WIKIBASE_PUBLIC_HOST=${env.WIKIBASE_PUBLIC_HOST}`,
    `WDQS_PUBLIC_HOST=${env.WDQS_PUBLIC_HOST}`,
    `MW_ADMIN_NAME=${env.MW_ADMIN_NAME}`,
    `MW_ADMIN_EMAIL=${env.MW_ADMIN_EMAIL}`,
    `MW_ADMIN_PASS=${env.MW_ADMIN_PASS}`,
    `DB_NAME=${env.DB_NAME}`,
    `DB_USER=${env.DB_USER}`,
    `DB_PASS=${env.DB_PASS}`,
    `METADATA_CALLBACK=${env.METADATA_CALLBACK}`
  ];

  try {
    fs.writeFileSync(path.join(DEPLOY_DIR, '.env'), lines.join('\n') + '\n');
    console.log('.env written successfully');
    res.status(200).json({ status: 'ok', generated: env });
  } catch (err) {
    console.error('Failed to write .env:', err);
    res.status(500).send('Failed to write .env');
  }
});

// Stop the container
app.post('/shutdown', (req, res) => {
  res.send('Shutting down...');
  exec('sleep 1 && kill 1');
});

app.listen(port, () => {
  console.log(`Installer webserver running at http://localhost:${port}`);
});
