import express from 'express';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { exec } from 'child_process';
import https from 'https';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Constants
const DEPLOY_DIR = '/data';
const CERT_PATH = path.join('/certs', 'cert.pem');
const KEY_PATH = path.join('/certs', 'key.pem');
const LOG_PATH = '/log/deploy-setup.log';
const HTTPS_PORT = 443;

// Init
const app = express();
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());

// Helpers
function generatePassword() {
  return crypto.randomBytes(12).toString('base64');
}

function getPublicIP() {
  return new Promise((resolve, reject) => {
    https.get('https://api.ipify.org', (res) => {
      let ip = '';
      res.on('data', chunk => ip += chunk);
      res.on('end', () => resolve(ip.trim()));
    }).on('error', reject);
  });
}

function buildEnvContent(input, publicIP) {
  const fallbackHost = `${publicIP}.nip.io`;

  const env = {
    WIKIBASE_PUBLIC_HOST: input.WIKIBASE_PUBLIC_HOST || fallbackHost,
    WDQS_PUBLIC_HOST: input.WDQS_PUBLIC_HOST || `query.${fallbackHost}`,
    MW_ADMIN_NAME: input.MW_ADMIN_NAME || 'admin',
    MW_ADMIN_EMAIL: input.MW_ADMIN_EMAIL || 'admin@wikibase.example',
    MW_ADMIN_PASS: input.MW_ADMIN_PASS || generatePassword(),
    DB_NAME: input.DB_NAME || 'my_wiki',
    DB_USER: input.DB_USER || 'sqluser',
    DB_PASS: input.DB_PASS || generatePassword(),
    METADATA_CALLBACK: input.METADATA_CALLBACK === 'true'
  };

  const lines = [
    '# Autogenerated .env file from installer UI',
    ...Object.entries(env).map(([k, v]) => `${k}=${v}`)
  ];

  return { env, content: lines.join('\n') + '\n' };
}

// Routes
app.get('/log', (req, res) => {
  if (!fs.existsSync(LOG_PATH)) return res.status(404).send('Log not found');

  fs.readFile(LOG_PATH, 'utf8', (err, data) => {
    if (err) {
      console.error('Error reading log:', err);
      return res.status(500).send('Error reading log');
    }
    res.type('text/plain').send(data);
  });
});

app.post('/write-env', async (req, res) => {
  try {
    const publicIP = await getPublicIP().catch(() => '127.0.0.1');
    const { env, content } = buildEnvContent(req.body, publicIP);

    fs.writeFileSync(path.join(DEPLOY_DIR, '.env'), content);
    console.log('.env file written successfully');

    res.status(200).json({ status: 'ok', generated: env });
  } catch (err) {
    console.error('Failed to write .env:', err);
    res.status(500).send('Failed to write .env');
  }
});

app.post('/shutdown', (req, res) => {
  res.send('Shutting down...');
  exec('sleep 1 && kill 1');
});

// HTTPS server setup
if (!fs.existsSync(CERT_PATH) || !fs.existsSync(KEY_PATH)) {
  console.error('Missing SSL certificate or key in /certs');
  process.exit(1);
}

const credentials = {
  key: fs.readFileSync(KEY_PATH),
  cert: fs.readFileSync(CERT_PATH)
};

https.createServer(credentials, app).listen(HTTPS_PORT, () => {
  console.log(`HTTPS server running at https://localhost:${HTTPS_PORT}`);
});
