on:
  workflow_call:

env:
  BUILD_CACHE_REGISTRY: ghcr.io/${{ github.repository_owner }}/wikibase
  BUILD_CACHE_PUSH: "true"

jobs:
  skip_check:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Check for duplicate successful runs
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["docs/**", "**/*.md", "**/*.txt", "*.md", "*.txt"]'
          skip_after_successful_duplicate: true
          cancel_others: true
          do_not_skip: '["schedule"]'

  lint:
    needs:
      - skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerhub_token: ${{ secrets.WBS_PUBLISH_TOKEN }}

      - run: ./wbs-dev lint
        working-directory: development

  build:
    needs:
      - skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        imageName:
          - wikibase
          - opensearch
          - wbs-tools
          - wdqs
          - wdqs-frontend
          - quickstatements

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerhub_token: ${{ secrets.WBS_PUBLISH_TOKEN }}

      - name: Build and push ${{ matrix.imageName }}
        run: ./wbs-dev build ${{ matrix.imageName }} --push
        working-directory: development

  test:
    needs:
      - skip_check
      - build
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      WBS_TEST_IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/wikibase
      WBS_TEST_IMAGE_TAG: dev-${{ github.run_id }}

    strategy:
      fail-fast: false
      matrix:
        suite:
          - wbs-dev-tools
          - repo
          - extensions
          - queryservice
          - repo-client
          - quickstatements
          - pingback
          - opensearch
          - wbs-tools

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerhub_token: ${{ secrets.WBS_PUBLISH_TOKEN }}

      - name: Run wbs-dev tooling test suite
        if: matrix.suite == 'wbs-dev-tools'
        run: ./wbs-dev test wbs-dev-tools
        working-directory: development

      - name: "Run ${{ matrix.suite }} integration test suite"
        if: matrix.suite != 'wbs-dev-tools'
        run: ./wbs-dev test ${{ matrix.suite }} --skip-build
        working-directory: development

      - name: Show logs
        if: failure() && matrix.suite != 'wbs-dev-tools'
        run: |
          ls -lahr development/tests/${{ matrix.suite }}/results development/tests/${{ matrix.suite }}/results/*
          tail -n +1 development/tests/${{ matrix.suite }}/results/*.log
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: failure() && matrix.suite != 'wbs-dev-tools'
        with:
          name: dev-${{ github.run_id }}-${{ matrix.suite }}-test-results
          path: development/tests/*/results
