name: 📦🛸 Publish to Dockerhub 🐳❤️

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Github Workflow run_id'
        required: true
        default: ''

env:
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  # env_file: ${{ github.event.inputs.env_file }}
  # WORKFLOW_RUN_NUMBER: ${{ github.event.inputs.workflow_run_number }}

jobs:
  publish_docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component:
          [
            "wikibase",
            "wikibase-bundle",
            "elasticsearch",
            "wdqs",
            "wdqs-frontend",
            "wdqs-proxy",
            "quickstatements",
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        shell: bash
        run: |
          cat variables.env

          echo "Workflow run id" ${{ inputs.workflow_run_id }}

      - name: Pull earlier build for cache reuse
        shell: bash
        run: |
          set -x

          source ./variables.env

          image_name="${{ matrix.component }}"
          tag="${{ inputs.workflow_run_id }}"

          docker pull ghcr.io/${{ github.repository_owner }}/wikibase/"$image_name":"$tag"

