name: 📦🛸 Publish to Dockerhub

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Github Build Workflow run_id'
        required: true
        default: ''

env:
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  publish_docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component:
          [
            # TODO: remove one of them with https://phabricator.wikimedia.org/T347000
            "wikibase",
            "wikibase-bundle",
            "elasticsearch",
            "wdqs",
            "wdqs-frontend",
            "wdqs-proxy",
            "quickstatements",
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Publish built images from GHCR to Dockerhub
        shell: bash
        run: |
          set -x

          # Get the version strings from the variables file of this branch.
          source ./variables.env

          image_name="${{ matrix.component }}"

          # The github actions run the image was built in. This id is also used
          # to tag the built container, so will be used to reference the image
          # when pulling it from GHCR.
          run_id_tag="${{ inputs.workflow_run_id }}"

          # The version string used for the container upon push to dockerhub.
          # This is the publicly visible version.
          # TODO: cleanup with upcoming versioning scheme
          version_tag="${WMDE_RELEASE_VERSION}"

          if [ "${{ matrix.component }}" = "wikibase" ]; then
            version_tag="${MEDIAWIKI_VERSION}-${WMDE_RELEASE_VERSION}"
          fi
          if [ "${{ matrix.component }}" = "wikibase-bundle" ]; then
            version_tag="${MEDIAWIKI_VERSION}-${WMDE_RELEASE_VERSION}"
          fi
          if [ "${{ matrix.component }}" = "wdqs" ]; then
            version_tag="${WDQS_VERSION}-${WMDE_RELEASE_VERSION}"
          fi
          if [ "${{ matrix.component }}" = "elasticsearch" ]; then
            version_tag="${ELASTICSEARCH_VERSION}-${WMDE_RELEASE_VERSION}"
          fi

          # Get the built image from GHCR for the given workflow run_id.
          docker pull ghcr.io/${{ github.repository_owner }}/wikibase/"$image_name":"$run_id_tag"

          # Retag the image with the final version string for dockerhub.
          docker tag ghcr.io/${{ github.repository_owner }}/wikibase/"$image_name":"$run_id_tag" wikibase/"$image_name":"$version_tag"

          # Push the image to dockerhub.
          docker push wikibase/"$image_name":"$version_tag"
